version = 5.8.0
archive_dir = /etc/letsencrypt/archive/api.jeevanandan.me
cert = /etc/letsencrypt/live/api.jeevanandan.me/cert.pem
privkey = /etc/letsencrypt/live/api.jeevanandan.me/privkey.pem
chain = /etc/letsencrypt/live/api.jeevanandan.me/chain.pem
fullchain = /etc/letsencrypt/live/api.jeevanandan.me/fullchain.pem
[renewalparams]
account = 0a4e25c619cb60f807d8157cd4064bd4
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
api.jeevanandan.me = /var/www/certbot
